[patch] Make Manage's defaultJMS configurable
ibm-mas/ansible-devops pull request #1000
Opened 2023-09-07 01:01 UTC by alequint

2023-09-08 09:03 UTC, whitfiea requested changes

2023-09-08 09:03 UTC, whitfiea commented on ibm/mas_devops/roles/suite_app_config/README.md
> +- Environment Variable: `mas_app_settings_default_jms`
Should be uppercase?

2023-09-08 17:46 UTC, alequint commented on ibm/mas_devops/roles/suite_app_config/README.md
> +- Environment Variable: `mas_app_settings_default_jms`
Yes!

2023-09-08 17:48 UTC, alequint commented on ibm/mas_devops/roles/suite_app_config/README.md
> +- Environment Variable: `mas_app_settings_default_jms`
Done!

2023-09-12 09:10 UTC, alequint commented
@andrercm @whitfiea could you please review it again and approve it if possible?

2023-09-12 11:16 UTC, merged