[patch] Add suite_app_uninstall role
ibm-mas/ansible-devops pull request #1035
Opened 2023-10-06 07:56 UTC by stonepd

Include a role to uninstall MAS Applications

Issue: https://jsw.ibm.com/browse/MASCORE-225 

Initially tested by uninstalling IoT and Monitor in `mastechfoundation` cluster

2023-10-12 09:35 UTC, durera requested changes
Can you add the new role to copyroledocs build script and to mkdocs index, other than that looks good.

2023-10-13 13:02 UTC, andrercm approved these changes
looks good

2023-10-24 08:19 UTC, stonepd commented
> Can you add the new role to copyroledocs build script and to mkdocs index, other than that looks good.

@durera  - Andre's changes have addressed this so can you approve please?

2023-10-24 11:28 UTC, durera approved these changes

2023-10-24 11:31 UTC, merged