[patch] Initial changes to support CPD 4.8 mirroring
ibm-mas/ansible-devops pull request #1275
Opened 2024-04-18 20:41 UTC by andrercm

2024-05-07 09:25 UTC, whitfiea requested changes
@andrercm This seems to have removed the cp4d 4.8.1 mirror_extra_perpare vars but the catalog_source replacement is just 4.8.0. What happens if the CPD_PRODUCT_VERSION is 4.8.1?

2024-05-07 11:46 UTC, andrercm commented
@whitfiea at this point we are just going to support CPD 4.8.0, once it's in, then we will later on decide which CPD patch to support, that's why i removed 4.8.1 to avoid confusion on which version to use.

2024-05-20 15:02 UTC, sanjayprab approved these changes

2024-05-21 06:17 UTC, whitfiea approved these changes

2024-05-21 06:34 UTC, merged