[patch] MASCORE-2328: Fix ibm-entitlement-key lookup while dro_migration
ibm-mas/ansible-devops pull request #1277
Opened 2024-04-19 14:33 UTC by yuvraj-vansure

[MASCORE-2328](https://jsw.ibm.com/browse/MASCORE-2328): update-uds task fails when ibm_entitlement_key secret is not avaliable on ibm-common-services namespace, added chnages to look at core namespace and pick up the ibm-entitlement-key.

2024-04-23 17:25 UTC, lokesh-sreedhara approved these changes

2024-04-23 17:27 UTC, andrercm requested changes

2024-04-24 11:14 UTC, yuvraj-vansure commented on ibm/mas_devops/roles/dro/tasks/install-dro/main.yml
> +        - name: set insatnce namespace
fixed

2024-04-24 12:43 UTC, andrercm approved these changes

2024-04-24 14:51 UTC, merged