[patch] support DRO in ibm-software-central namesapce
ibm-mas/ansible-devops pull request #1342
Opened 2024-06-18 16:04 UTC by lokesh-sreedhara

"DRO operator v2.16.0 is published and defaults namespace to` ibm-software-central`. the role bindings are created for that namespace, as well as the legacy default namespaces so, should not impact upgrade, and for new deployments, you can use` ibm-software-central` namespace if you wish."

This PR is to change the DRO default namespace to ` ibm-software-central`

2024-06-19 13:34 UTC, yuvraj-vansure approved these changes

2024-06-20 08:16 UTC, whitfiea requested changes
@lokesh-sreedhara This would have to be a major change I believe as you are changing the default. If someone ran this role before this change, and then runs it after this change on the same environment, then you would have DRO installed twice? We would need some type of migration path so we don't duplicate deployments

2024-06-20 14:56 UTC, lokesh-sreedhara commented
> @lokesh-sreedhara This would have to be a major change I believe as you are changing the default. If someone ran this role before this change, and then runs it after this change on the same environment, then you would have DRO installed twice? We would need some type of migration path so we don't duplicate deployments

@whitfiea hmm. yea if it would install it twice if users install old version and then the newer version. thinking how to handle this.

2024-11-07 10:49 UTC, whitfiea commented
https://github.com/ibm-mas/cli/pull/1040 is closed as won't do, so closing this as well

2024-11-07 10:49 UTC, closed without merging