[patch] Fixes and updates for IBMCloud COS support
ibm-mas/ansible-devops pull request #1555
Opened 2024-11-13 15:52 UTC by twhart

Setup COS so it doesn't rely on the ibmcloud_apikey if the cos_apikey has been set. This allows for a less privileged apikey to be used. Renamed some variables to align more closely to how the rest of COS is used

Tested here:
https://dashboard.masdev.wiotp.sl.hursley.ibm.com/tests/pfvtcos

See also: MASCORE-4345

2024-11-13 16:02 UTC, twhart commented
Closes #1346

2024-11-14 11:18 UTC, durera requested changes

2024-11-14 11:18 UTC, durera commented on ibm/mas_devops/roles/cos_bucket/README.md
I don't think we should rename this here, it will make this update incompatible with previous, and the instance name is fine to stay as "x-ibmcos-x"

2024-11-14 11:18 UTC, durera commented on ibm/mas_devops/roles/cos/templates/ibm/objectstoragecfg.yml.j2
I think we should keep the same names here, it will avoid this becoming incompatible with previous runs, and there's no specific reason the name of the secret needs to change,

2024-11-14 19:19 UTC, durera approved these changes

2024-11-14 19:22 UTC, merged