[patch] Aibroker update playbook for install specific ODH version
ibm-mas/ansible-devops pull request #1588
Opened 2024-12-09 15:56 UTC by karol-czarnecki

https://jsw.ibm.com/browse/MASAIB-517

2025-01-14 09:01 UTC, whitfiea requested changes
The PR needs more description. Why did we need to move away from ibm.mas_devops.apply_subscription and use a subscription.yaml?

It is also updating versions of images

2025-01-14 10:56 UTC, karol-czarnecki commented on ibm/mas_devops/roles/odh/tasks/odh-operator.yml
> +
Hi Andrew - here https://github.com/ibm-mas/ansible-devops/blob/6765437edb633d96444f10a5582a03ccb20830cf/ibm/mas_devops/common_tasks/templates/subscription.yml.j2#L30 we have defined `installPlanApproval: Automatic` we need to have `installPlanApproval: Manual` https://github.com/ibm-mas/ansible-devops/blob/6765437edb633d96444f10a5582a03ccb20830cf/ibm/mas_devops/roles/odh/templates/odh/subscription.yml.j2#L8 if we want to install specific version. We need then approve install plan

2025-01-14 10:57 UTC, karol-czarnecki commented on ibm/mas_devops/roles/aibroker/tasks/watsonx/install/main.yml
> +    - '{{ tenantNamespace }}----wx-secret'
here we create WX secret in aibroker namespace and then we need copy this secret to tenant we use

2025-01-14 10:59 UTC, karol-czarnecki commented on ibm/mas_devops/roles/odh/tasks/odh-operator.yml
> +
when we use Automatic it is deploying latest version from channel

2025-01-14 12:26 UTC, karol-czarnecki commented on ibm/mas_devops/roles/kmodels/templates/kmodels-watcher/configmap.yml.j2
> +  CONTROLLER_URL: "https://km-controller:8443"
Watcher now gets tenants from the storage directly, not from configuration
We added parameter which specify the controller URL in the cluster.

2025-03-10 10:35 UTC, whitfiea commented on ibm/mas_devops/roles/odh/tasks/odh-operator.yml
> +
@karol-czarnecki can we delete the code rather than just comment it out?

2025-03-10 10:41 UTC, karol-czarnecki commented on ibm/mas_devops/roles/odh/tasks/odh-operator.yml
> +
Hi @whitfiea 

not needed code removed

2025-03-10 10:49 UTC, merged