[patch] add task to create norootsquash daemonset for nfs based db2 m…
ibm-mas/ansible-devops pull request #172
Opened 2022-03-03 16:48 UTC by cuddlyporcupine

…eta volumes

2022-03-03 19:16 UTC, andrercm approved these changes

2022-03-07 15:25 UTC, durera requested changes
Could you add something to the readme in this role that explains how this is working/what the logic is for this support of NFS volumes.

Does the user need to manually create this daemonset, or is it created automatically?  I can see that the `setup_norootsquash` task creates the daemonset, but that task is only included if the daemonset already exists ... how does it get onto the system the first time this is ran?

2022-03-07 15:25 UTC, durera commented on ibm/mas_devops/roles/cp4d_db2wh/tasks/setup_norootsquash.yml
> +  delay: 60 # 1 minute
Linting failure .. missing a newline here

2022-03-07 15:25 UTC, durera commented on ibm/mas_devops/roles/cp4d_db2wh/tasks/setup_norootsquash.yml
> +    definition: "{{ lookup('template', 'templates/norootsquash_deamonset.yml') }}"
This template doesn't appear to exist: https://github.com/ibm-mas/ansible-devops/tree/norootsquash/ibm/mas_devops/roles/cp4d_db2wh/templates

2022-03-07 18:28 UTC, durera approved these changes

2022-03-07 19:17 UTC, merged