[minor] Add support for manual public cert management
ibm-mas/ansible-devops pull request #501
Opened 2022-11-04 12:02 UTC by sanju7216

Adding support to enable manual public certificate management mode. 
Using manual cert mgmt mode allows users to use their own public tls certificates rather than using IBM Cert manager's.

Manual mode can be enabled by having these env vars `MAS_MANUAL_CERT_MGMT=true` and `MAS_PUBLIC_CERT_DATA_PATH=pathToYamlFile`

A new role "manage_publiccert" is added to handle the TLS cert secret creation. This secret will then be processed by the MAS operator.

install_suite role uses the above new role to create the secret before suite CR in created, also adds a new field `spec.settings.manualCertMgmt` boolean field to suite CR to determine the certificate mgmt mode across the suite.

https://github.com/ibm-mas/ansible-devops/issues/500

2022-11-04 13:55 UTC, durera requested changes
As discussed on Slack

2023-05-03 09:41 UTC, alequint commented on ibm/mas_devops/roles/suite_install/templates/core_v1_suite.yml.j2
> +    manualCertMgmt: {{  mas_manual_cert_mgmt  }}
Already added by Sanjay here https://github.com/ibm-mas/ansible-devops/blob/manualcertmgmt/ibm/mas_devops/roles/suite_install/templates/core_v1_suite.yml.j2#L31

2023-05-03 09:54 UTC, alequint commented on ibm/mas_devops/rebuild.sh
To be removed before creating official PR

2023-05-03 09:54 UTC, alequint commented on ibm/mas_devops/roles/cert_manual_order/meta/main.yml
> +galaxy_info:
This role may fit better in ansible-fvt as it is very specific for an initial load of CNAMES in CIS to be used by Secrets Manager to generate the certificate

2023-05-16 09:14 UTC, durera requested changes
I'm not convinced about the relationship between the two roles `suite_certs` and `suite_dns` at this point, it feels a bit hokey  .. we might in the future want to look at combining them given the overlap we now have, but right now it's more important to get support for this feature integrated after the delays.

There's a few minor things to fix before we merge, see individual comments.

2023-05-16 09:14 UTC, durera commented on ibm/mas_devops/roles/suite_certs/meta/main.yml
> +  author: Sanjay Prabhakar & Alexandre Quinteiro
This should be converted to a list:

```
author: 
  - Sanjay Prabhakar
  - Alexandre Quinteiro
```

2023-05-16 09:14 UTC, durera commented on ibm/mas_devops/roles/suite_certs/tasks/main.yml
> +    msg: "mas_manual_cert_mgmt is not True, indicating the installation is using cert-managet to create certificates. This role will not take any action"
Typo in message

2023-05-16 09:16 UTC, durera commented on ibm/mas_devops/roles/suite_certs/meta/main.yml
> +  author: Sanjay Prabhakar & Alexandre Quinteiro
Fixed

2023-05-16 09:16 UTC, durera commented on ibm/mas_devops/roles/suite_certs/tasks/main.yml
> +    msg: "mas_manual_cert_mgmt is not True, indicating the installation is using cert-managet to create certificates. This role will not take any action"
Fixed

2023-05-16 10:15 UTC, durera approved these changes

2023-05-16 10:18 UTC, merged