[minor] Added Deprovisioning capability in cos role
ibm-mas/ansible-devops pull request #526
Opened 2022-11-22 08:43 UTC by Ashish-Mahawal1

As a part of Merging activity of SRE devops ibmcloud_cos role to mas_devops cos role 
1. Added IBM COS Instance de-provisioning play
2. Added Env `COS_DEPROVISION` with default value as `False` 
3. Set `COS_DEPROVISION` as True to deprovision COS Instance

2022-11-23 18:57 UTC, andrercm reviewed
Looks good! I just didn't found the assertions piece to validate whether the cos instance was provisioned or deprovisioned at the end of the process.

2022-11-24 08:36 UTC, Ashish-Mahawal1 commented
> Looks good! I just didn't found the assertions piece to validate whether the cos instance was provisioned or deprovisioned at the end of the process.

Added those assertions as well :)

2022-12-06 18:57 UTC, durera requested changes
Also needs updates to the changelogs as this is a minor update

2022-12-06 19:02 UTC, andrercm commented on ibm/mas_devops/roles/cos_bucket/README.md
> +This role
Sorry, didn't notice that before final commit, that's what i get when working on docs while joining lots of calls lol
Just fixed it

2022-12-06 19:06 UTC, andrercm commented on ibm/mas_devops/roles/suite_app_config/tasks/main.yml
> +- name: Gen certs file
Initially added this to debug the output of the manageworkspace cr, wont use at all though, so just cleaned it

2022-12-06 19:11 UTC, andrercm commented on ibm/mas_devops/roles/suite_app_config/tasks/main.yml
> +- name: Gen certs file
Done

2022-12-06 19:54 UTC, durera approved these changes

2022-12-06 19:55 UTC, merged