[minor] Added CIS Role from SRE devops to MAS devops
ibm-mas/ansible-devops pull request #549
Opened 2022-12-08 07:59 UTC by Ashish-Mahawal1

Issue :  https://github.ibm.com/wiotp/tracker/issues/10620

Changes :
1. Added new role `cis` to mas_devops

### Provisioning flow
```
a. Provision CIS Instance in customer account
b. Add customer domain to customer's CIS Instance
c. Configure Domain settings in customer CIS Instance
d. Add DNS Records of type `NS` for customer's Domain nameservers to Master CIS Account
```

### Deprovisioning Flow
```
a. Delete DNS Record from Master Account
b. Delete Domain from Customer Account
c. Delete Customer CIS Instance
```

Flow Diagram 

![CIS Role updated](https://user-images.githubusercontent.com/100187956/206223755-ecd7ceb5-588e-455c-b912-de236a66e9b2.png)

### Testing
Manual Tests
1. Tested provisioning flow when no resources already exists 
2. Tested deprovisioing flow when all CIS related resources exists
3. Tested provisioning flow when all resources already exists
4. Tested deprovisioing flow when some CIS related resources does not exists

2022-12-29 14:40 UTC, Ashish-Mahawal1 commented on ibm/mas_devops/roles/cis/defaults/main.yml
> +master_cis_resource_name: "{{ lookup('env', 'MASTER_CIS_RESOURCE_NAME') | default('masms-cis', True) }}"
change  default value to <mas-instance-id>-cis

2022-12-29 14:41 UTC, Ashish-Mahawal1 commented on ibm/mas_devops/roles/cis/defaults/main.yml
> +masms_base_domain: "{{ lookup('env', 'MASMS_BASE_DOMAIN') | default('suite.maximo.com', True) }}"
rename var to master_cis_...
remove default value

2023-01-04 14:47 UTC, durera requested changes

2023-01-04 14:47 UTC, durera commented on ibm/mas_devops/roles/cis/meta/main.yml
> +  description: Configure ceph object storage or ibm cloud object storage for MAS Assist
This should be corrected

2023-01-04 14:47 UTC, durera commented on docs/changes.md
> +- `12.6` Support IBM CIS provisioning deprovisioning ([#549](https://github.com/ibm-mas/ansible-devops/pull/549/))
Merge from master and update the other changelog too

2023-01-04 14:47 UTC, durera commented on build/bin/copy-role-docs.sh
> +copyDoc cis
add this in alphabetical order like the rest please.  Also add this to appropriate section in mkdocs.yml

2023-01-04 15:07 UTC, Ashish-Mahawal1 commented on ibm/mas_devops/roles/cis/meta/main.yml
> +  description: Configure ceph object storage or ibm cloud object storage for MAS Assist
done

2023-01-04 15:17 UTC, merged