Support backup and restore for MongoDB provider ibm
ibm-mas/ansible-devops pull request #623
Opened 2023-01-24 09:48 UTC by Ashish-Mahawal1

Issue: https://github.ibm.com/wiotp/tracker/issues/10595

Mongo DB Role now supports Backup and restore functionality for Provider IBM

Testing:

Testing Manually 
1. Backing up an existing MongoDB
2. Restoring from a backed up MongoDB Instance using the Backup ID/CRN

2023-01-24 17:23 UTC, Ashish-Mahawal1 commented on ibm/mas_devops/roles/mongodb/tasks/providers/ibm/restore.yml
> +    ibm_mongo_service_endpoints: "public"
make this param configurable

2023-01-27 09:11 UTC, Ashish-Mahawal1 commented on ibm/mas_devops/roles/mongodb/tasks/providers/ibm/restore.yml
> +    ibm_mongo_service_endpoints: "public"
done

2023-02-02 17:41 UTC, durera requested changes
Should be a minor update, needs a corresponding update to the changelogs

2023-03-13 10:39 UTC, durera approved these changes

2023-03-13 10:42 UTC, merged