[patch] Add non-olm to olm conversion script
ibm-mas/ansible-devops pull request #691
Opened 2023-03-04 17:47 UTC by rawa-resul

## Description

- Added a new role 'convert_to_olm'
- Added new playbook 'oneclick_convert_to_olm'

The new role converts an existing non-olm installed instance of MAS/Application into an olm channel subscription.

2023-03-04 20:08 UTC, rawa-resul commented
an example run:
```bash
rawa.resulibm.com@Rawas-MacBook-Pro mas_devops % ansible-playbook oneclick_convert_to_olm.yml
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [Convert to OLM Playbook] *************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************************
ok: [localhost]

TASK [Check for required environment variables] ********************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [ibm.mas_devops.ansible_version_check : Verify minimum Ansible version is 2.10.3] *****************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [convert_to_olm : Assert that mas_instance_id is defined] *****************************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [convert_to_olm : Assert that mas_app_id is defined] **********************************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [convert_to_olm : Assert that mas_app_id is supported] ********************************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [convert_to_olm : Validate required variables for ibm-entitlement] ********************************************************************************
ok: [localhost]

TASK [convert_to_olm : Assert that required variables are set for ibm-entitlement] *********************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [convert_to_olm : Set mas_app_operator_name fact] *************************************************************************************************
ok: [localhost]

TASK [convert_to_olm : Debug Information] **************************************************************************************************************
ok: [localhost] => {
    "msg": [
        "MAS Instance ID ........ rawa892",
        "MAS App ID ............. core",
        "MAS App Namespace ...... mas-rawa892-core",
        "MAS Upgrade Strategy ... Manual"
    ]
}

TASK [convert_to_olm : Lookup Current CR: Suite] *******************************************************************************************************
ok: [localhost]

TASK [convert_to_olm : Set found_app_cr fact] **********************************************************************************************************
ok: [localhost]

TASK [convert_to_olm : CR Not Found: Suite] ************************************************************************************************************
skipping: [localhost]

TASK [convert_to_olm : Reset Channel and startingCSV Facts] ********************************************************************************************
ok: [localhost]

TASK [convert_to_olm : Set Deployed Version: MAS] ******************************************************************************************************
ok: [localhost]

TASK [convert_to_olm : Debug Channel and startingCSV] **************************************************************************************************
ok: [localhost] => {
    "msg": [
        "app_channel ............... 8.9.x",
        "app_starting_csv .......... ibm-mas.v8.9.2"
    ]
}

TASK [convert_to_olm : 'status.versions.reconciled' Not Found] *****************************************************************************************
skipping: [localhost]

TASK [convert_to_olm : Lookup Existing Subscription] ***************************************************************************************************
ok: [localhost]

TASK [convert_to_olm : Set found_app_subscription fact] ************************************************************************************************
ok: [localhost]

TASK [convert_to_olm : Existing Subscription Found] ****************************************************************************************************
ok: [localhost] => {
    "msg": "Found existing Subscription for MAS  - Skipping conversion"
}

TASK [convert_to_olm : Delete Operator Deployment: MAS] ************************************************************************************************
skipping: [localhost]

TASK [convert_to_olm : Find existing TM Subscription] **************************************************************************************************
skipping: [localhost]

TASK [convert_to_olm : Set _app_tm_current_csv fact] ***************************************************************************************************
skipping: [localhost]

TASK [convert_to_olm : Delete TM Subscription] *********************************************************************************************************
skipping: [localhost]

TASK [convert_to_olm : Delete TM CSV] ******************************************************************************************************************
skipping: [localhost]

TASK [convert_to_olm : Delete TM Operator Deployment] **************************************************************************************************
skipping: [localhost]

TASK [convert_to_olm : Find existing OperatorGroup(s)] *************************************************************************************************
skipping: [localhost]

TASK [convert_to_olm : Delete Existing OperatorGroup(s)] ***********************************************************************************************
skipping: [localhost]

TASK [Install Operator: MAS] ***************************************************************************************************************************
skipping: [localhost]

TASK [convert_to_olm : Lookup Operator install plan] ***************************************************************************************************
skipping: [localhost]

TASK [convert_to_olm : Approve the subscription install plan] ******************************************************************************************
skipping: [localhost]

TASK [convert_to_olm : Handle IBM Common Services InstallPlan approvals] *******************************************************************************
skipping: [localhost] => (item=ibm-common-service-operator.ibm-common-services) 
skipping: [localhost] => (item=ibm-namespace-scope-operator.ibm-common-services) 
skipping: [localhost] => (item=ibm-odlm.ibm-common-services) 
skipping: [localhost] => (item=ibm-licensing-operator-app.ibm-common-services) 
skipping: [localhost]

TASK [convert_to_olm : Assert that mas_instance_id is defined] *****************************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [convert_to_olm : Assert that mas_app_id is defined] **********************************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [convert_to_olm : Assert that mas_app_id is supported] ********************************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [convert_to_olm : Validate required variables for ibm-entitlement] ********************************************************************************
ok: [localhost]

TASK [convert_to_olm : Assert that r [...]

2023-03-14 10:14 UTC, durera requested changes
Updated to a minor, need a changelog update .. also can we adjust the role's README to align with the layout ...

eg. instead of

### var_name
**Required** blah blah blah

- Env Var: xxx
- Default: xxx

It should be


### var_name
Blah blah blah

- **Required** 
- Env Var: xxx
- Default: xxx

Ref: https://ibm-mas.github.io/ansible-devops/roles/sls/ (not all the original role READMEs have been updated to this model yet, but all new ones are and slowly working through the older ones )

2023-03-14 14:48 UTC, rawa-resul commented
> Updated to a minor, need a changelog update .. also can we adjust the role's README to align with the layout ...
> 
> eg. instead of
> ### var_name
> 
> **Required** blah blah blah
> 
>     * Env Var: xxx
> 
>     * Default: xxx
> 
> 
> It should be
> ### var_name
> 
> Blah blah blah
> 
>     * **Required**
> 
>     * Env Var: xxx
> 
>     * Default: xxx
> 
> 
> Ref: https://ibm-mas.github.io/ansible-devops/roles/sls/ (not all the original role READMEs have been updated to this model yet, but all new ones are and slowly working through the older ones )

Thanks. I have updated the README accordingly.

2023-03-21 13:58 UTC, durera approved these changes

2023-03-21 14:03 UTC, merged