[minor] Support AWS MSK as Kafka provider
ibm-mas/ansible-devops pull request #727
Opened 2023-03-24 15:19 UTC by padmankosalaram

- [x] add support for aws msk provision and deprovision
- [x] aws provision was tested as part of https://github.ibm.com/maximoappsuite/tracker-hyperscalers/issues/239
- [x] aws deprovision was tested as part of https://github.ibm.com/maximoappsuite/tracker-hyperscalers/issues/240 

Please review the pr and provide your comments.

2023-03-28 11:49 UTC, durera requested changes
Also need changelog updates as this is a new feature

2023-03-29 17:43 UTC, padmankosalaram commented on ibm/mas_devops/roles/kafka/README.md
> +- Default Value: `provision`
KAFKA_ACTION provision / deprovision was updated as install / uninstall. 
The related file names were modified to install.yml and uninstall.yml + reference in ReadMe

2023-03-29 17:44 UTC, padmankosalaram commented on ibm/mas_devops/roles/kafka/README.md
> +- Default Value: `provision`
Change logs was updated with PR 727 details

2023-03-30 08:42 UTC, padmankosalaram commented
Tested as part of https://github.ibm.com/maximoappsuite/tracker-hyperscalers/issues/265

2023-03-31 15:41 UTC, whitfiea submitted a review, later dismissed

2023-03-31 16:32 UTC, padmankosalaram commented
@durera @whitfiea @andrercm - This PR is ready for merge. I done with the review comments and testing. Please help with merge

2023-03-31 18:27 UTC, whitfiea approved these changes

2023-03-31 18:30 UTC, merged