[minor] Add support for Cloud Pak for Data 4.6.4
ibm-mas/ansible-devops pull request #785
Opened 2023-04-26 13:53 UTC by andrercm

- This PR adds support for CPD release 4.6.4, based on its official `olm-utils-cm` config map:
https://github.ibm.com/PrivateCloud/olm-utils/blob/master/ansible-play/config-vars/release-4.6.4.yml

- Also added a fix for #704:
  - Added a check to validate that common services version is installed and compatible with the target cpd release.
  - Added a check to validate that cpd is installed and ready before installing any cpd service.

Corresponding changes for cli: https://github.com/ibm-mas/cli/pull/262
Corresponding changes for ansible-fvt: https://github.ibm.com/maximoappsuite/ansible-fvt/pull/199

**Note: CPD 4.6.4 is not yet available in the Maximo Operator Catalog today, it will be available in the June update**

2023-05-02 16:59 UTC, whitfiea approved these changes

2023-05-02 21:59 UTC, sanju7216 approved these changes

2023-05-03 10:18 UTC, whitfiea requested changes
@andrercm As this is minor can you add the change log details

2023-05-04 19:53 UTC, andrercm commented
After fixing #704, we'll have extra assertions:

`cp4d` role:
```
TASK [ibm.mas_devops.cp4d : Assert that IBM Cloud Pak Foundational Services is compatible with Cloud Pak for Data version 4.6.4] **********************************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [ibm.mas_devops.cp4d : Debug IBM Cloud Pak Foundational Services Install] ************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": [
        "Subscription Channel defined ............................................................. v3.23",
        "Catalog Source ........................................................................... ibm-operator-catalog",
        "Current installed version ................................................................ v3.23.2",
        "Expected compatible version with CloudPak for Data 4.6.4 ................................. v3.23.1+"
    ]
}
```

`cp4d_service` role:
```
TASK [ibm.mas_devops.cp4d_service : Lookup Cloud Pak for Data] ****************************************************************************************************************************************************************************************
ok: [localhost]

TASK [ibm.mas_devops.cp4d_service : Check if Cloud Pak for Data is installed] *************************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [ibm.mas_devops.cp4d_service : Check if Cloud Pak for Data is healthy] ***************************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}
```

2023-05-05 08:58 UTC, whitfiea approved these changes
Approving, but we can only merge this when the curated catalog is released with 4.6.4 otherwise someone will try to install it and it won't work.

2023-05-19 14:19 UTC, whitfiea approved these changes

2023-05-23 21:09 UTC, durera approved these changes

2023-05-23 21:14 UTC, merged