[patch] Add tags to the extras mirror manifest files
ibm-mas/ansible-devops pull request #823
Opened 2023-05-18 13:46 UTC by PeterNiblett

This patch is for Airgap mirroring and is to resolve issue #804.  

Currently if you use the CLI to produce mirror manifest files, the ones that are  produced from CASE bundles (i.e. the mirror_case_prepare role) contain image tags but those like Mongo images,  produced by mirror_extras_prepare,  do not.

Some airgap mirror registries appear to require all images to be tagged. 

I have tested the mirror_extras_prepare role and have verified that the tags get included.

2023-05-18 15:52 UTC, durera requested changes
Not all extras have tags ... e.g. 

```
extra_images:
  - name: cpopen/ibm-cpd-cloud-native-postgresql-operator-bundle
    registry: icr.io
    digest: sha256:3279e5dc5cccc23aafb4c48192b7fc4585a80fe232b65f4e1f562448ed7fc3c8

  - name: cpopen/ibm-cpd-cloud-native-postgresql-operator
    registry: icr.io
    digest: sha256:4ef97266b00aa94b697065434a46f43f064c1254fac4dab993998c5068f541d7
```

Every file in `ibm/mas_devops/roles/mirror_extras_prepare/vars` would need to have tags for every image, or this would break for those that do not.

2023-06-02 09:30 UTC, PeterNiblett commented
I have made the addtion of the image tag conditional on the tag being defined in the vars file, so it won't now break if we don't have tags there.  I have also added the tags to the db2 extras files.   The only file that is currently missing tags is the wd extras one.

2023-06-06 14:56 UTC, PeterNiblett commented
> Not all extras have tags ... e.g.
> 
> ```
> extra_images:
>   - name: cpopen/ibm-cpd-cloud-native-postgresql-operator-bundle
>     registry: icr.io
>     digest: sha256:3279e5dc5cccc23aafb4c48192b7fc4585a80fe232b65f4e1f562448ed7fc3c8
> 
>   - name: cpopen/ibm-cpd-cloud-native-postgresql-operator
>     registry: icr.io
>     digest: sha256:4ef97266b00aa94b697065434a46f43f064c1254fac4dab993998c5068f541d7
> ```
> 
> Every file in `ibm/mas_devops/roles/mirror_extras_prepare/vars` would need to have tags for every image, or this would break for those that do not.



> This patch is for Airgap mirroring and is to resolve issue #804.
> 
> Currently if you use the CLI to produce mirror manifest files, the ones that are produced from CASE bundles (i.e. the mirror_case_prepare role) contain image tags but those like Mongo images, produced by mirror_extras_prepare, do not.
> 
> Some airgap mirror registries appear to require all images to be tagged.
> 
> I have tested the mirror_extras_prepare role and have verified that the tags get included.

2023-06-08 16:12 UTC, durera approved these changes

2023-06-08 16:18 UTC, merged