[patch] fix fyre api and conditions to provision or deprovision a quickburn
ibm-mas/ansible-devops pull request #889
Opened 2023-06-27 22:34 UTC by andrercm

2023-06-27 22:46 UTC, durera requested changes
As discussed in Slack

2023-06-28 01:20 UTC, andrercm commented
Tested with quickburn provisioning:

1. new provisioning:

```
TASK [ibm.mas_devops.ocp_provision : fyre : Debug cluster provision] ********************************************************************
ok: [localhost] => {
    "_cluster_create": {
        "changed": false,
        "connection": "close",
        "content_length": "109",
        "content_type": "application/json",
        "cookies": {},
        "cookies_string": "",
        "date": "Tue, 27 Jun 2023 23:18:19 GMT",
        "elapsed": 9,
        "failed": false,
        "json": {
            "cluster_name": "andrefyre",
            "details": "cluster build initiated",
            "request_id": "1-76843613",
            "status": "success"
        },
        "msg": "OK (109 bytes)",
        "redirected": false,
        "server": "Apache/2.4.41 (Ubuntu)",
        "server_timing": "intid;desc=110c2b17c42c6407",
        "status": 200,
        "strict_transport_security": "max-age=63072000; includeSubdomains",
        "url": "https://ocpapi.svl.ibm.com/v1/ocp/",
        "x_content_type_options": "nosniff",
        "x_frame_options": "DENY"
    }
}

TASK [ibm.mas_devops.ocp_provision : fyre : Follow deployment status (2 minute intervals)] **********************************************
FAILED - RETRYING: [localhost]: fyre : Follow deployment status (2 minute intervals) (60 retries left).
FAILED - RETRYING: [localhost]: fyre : Follow deployment status (2 minute intervals) (59 retries left).
FAILED - RETRYING: [localhost]: fyre : Follow deployment status (2 minute intervals) (58 retries left).
FAILED - RETRYING: [localhost]: fyre : Follow deployment status (2 minute intervals) (57 retries left).
FAILED - RETRYING: [localhost]: fyre : Follow deployment status (2 minute intervals) (56 retries left).
FAILED - RETRYING: [localhost]: fyre : Follow deployment status (2 minute intervals) (55 retries left).
FAILED - RETRYING: [localhost]: fyre : Follow deployment status (2 minute intervals) (54 retries left).
ok: [localhost]

PLAY RECAP ******************************************************************************************************************************
localhost                  : ok=14   changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
```

2. new provisioning, but aborting the cluster deployment status and rerunning (idempotent test):

```
TASK [ibm.mas_devops.ocp_provision : fyre : Debug cluster lookup] ****************************************************
ok: [localhost] => {
    "_cluster_exist": {
        "changed": false,
        "connection": "close",
        "content_length": "116",
        "content_type": "application/json",
        "cookies": {},
        "cookies_string": "",
        "date": "Wed, 28 Jun 2023 01:13:00 GMT",
        "elapsed": 1,
        "failed": false,
        "failed_when_result": false,
        "json": {
            "details": "name andrefyre2 is currently in use in domain cp.fyre.ibm.com",
            "owning_user": "16454",
            "status": "warning"
        },
        "msg": "OK (116 bytes)",
        "redirected": false,
        "server": "Apache/2.4.41 (Ubuntu)",
        "server_timing": "intid;desc=e848df1afeacc786",
        "status": 200,
        "strict_transport_security": "max-age=63072000; includeSubdomains",
        "url": "https://ocpapi.svl.ibm.com/v1/check_hostname/andrefyre2",
        "x_content_type_options": "nosniff",
        "x_frame_options": "DENY"
    }
}

TASK [ibm.mas_devops.ocp_provision : fyre : Create new OCP+ cluster] *************************************************
skipping: [localhost]

TASK [ibm.mas_devops.ocp_provision : fyre : Debug cluster provision] *************************************************
ok: [localhost] => {
    "_cluster_create": {
        "changed": false,
        "false_condition": "_cluster_exist.json.owning_user is not defined",
        "skip_reason": "Conditional result was False",
        "skipped": true
    }
}

TASK [ibm.mas_devops.ocp_provision : fyre : Follow deployment status (2 minute intervals)] ***************************
FAILED - RETRYING: [localhost]: fyre : Follow deployment status (2 minute intervals) (60 retries left).
FAILED - RETRYING: [localhost]: fyre : Follow deployment status (2 minute intervals) (59 retries left).
FAILED - RETRYING: [localhost]: fyre : Follow deployment status (2 minute intervals) (58 retries left).
ok: [localhost]

PLAY RECAP ***********************************************************************************************************
localhost                  : ok=13   changed=0    unreachable=0    failed=0    skipped=2    rescued=0    ignored=0   
```

2023-06-28 14:54 UTC, andrercm commented
@durera can you re-review it please?

2023-07-12 11:26 UTC, durera approved these changes

2023-07-12 11:30 UTC, merged