Healthfvt
ibm-mas/ansible-devops pull request #979
Opened 2023-08-22 23:16 UTC by alequint

2023-08-29 23:19 UTC, andrercm requested changes
just a minor typo found, other than that i think it's looking ok.

2023-08-29 23:19 UTC, andrercm commented on ibm/mas_devops/roles/suite_app_config/README.md
> +Optional. Boolean value indicating if Watson Studio must be bound to Manage. It is expected a sytem level WatsonStudioCfg applied in the cluster.
minor typo `sytem`

2023-08-30 04:09 UTC, alequint commented on ibm/mas_devops/roles/suite_app_config/README.md
> +Optional. Boolean value indicating if Watson Studio must be bound to Manage. It is expected a sytem level WatsonStudioCfg applied in the cluster.
done

2023-08-30 13:51 UTC, andrercm approved these changes
LGTM

2023-08-30 14:03 UTC, merged